alias: Hue Dimmer – multi-button handler
variables:
  light2_entity:
  step_size:
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:17:88:01:0b:d9:66:20
action:
  - choose:
#     # ---------- ON button ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light1_entity }}"
#    # ---------- OFF button ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'recall' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light1_entity }}"
#    # ---------- DIM-UP (short press) ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 0 }}"
          - "{{ trigger.event.data.params.step_size == 30 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light2_entity }}"
#    # ---------- DIM-UP (long press) ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 0 }}"
          - "{{ trigger.event.data.params.step_size == 63 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ light2_entity }}"
            data:
              brightness_step_pct: "{{ step_size }}"

#    # ---------- DIM-DOWN (short press) ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 1 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light2_entity }}"
#    # ---------- DIM-DOWN (long press) ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 1 }}"
          - "{{ trigger.event.data.params.step_size == 63 }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_step_pct: "{{ -step_size }}"
            target:
              entity_id: "{{ light2_entity }}"
#  # (optional) catch-all if you want to log unknown presses
  - service: system_log.write
    data:
      message: >
        Un-handled Hue press: EP {{trigger.event.data.endpoint_id}}
        cmd {{trigger.event.data.command}}
