alias: Hue Dimmer – multi-button handler
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "<IEEE>"
action:
  - choose:                        # ---------- ON button ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.<Light>
#    # ---------- OFF button ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'recall' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.<Light>
#    # ---------- DIM-UP (short press) ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.<Light>
#    # ---------- DIM-DOWN (short press) ----------
      - conditions:
          - "{{ trigger.event.data.endpoint_id == 1 }}"
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 1 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.<Light>
#  # (optional) catch-all if you want to log unknown presses
  - service: system_log.write
    data:
      message: >
        Un-handled Hue press: EP {{trigger.event.data.endpoint_id}}
        cmd {{trigger.event.data.command}}
